#pragma once

#include <cstdint>

// Per-font overlay placement ratios generated by extract_overlay_metrics.py.
// GfxRenderer uses these when drawing zero-advance Gujarati overlay glyphs.

struct GujaratiOverlayMetrics {
  uint16_t subjoinedRaOffsetNum;
  uint16_t subjoinedRaOffsetDen;
};

inline constexpr GujaratiOverlayMetrics kGujaratiOverlayMetricsDefault{201, 482};

inline int gujaratiSubjoinedRaX(const int lastConsX, const int consAdvancePx,
                                const GujaratiOverlayMetrics& metrics = kGujaratiOverlayMetricsDefault) {
  if (consAdvancePx <= 0 || metrics.subjoinedRaOffsetDen == 0) {
    return lastConsX;
  }
  return lastConsX + consAdvancePx - (consAdvancePx * metrics.subjoinedRaOffsetNum / metrics.subjoinedRaOffsetDen);
}

// Rotated drawText uses a decreasing Y pen; mirror the subjoined-Ra offset.
inline int gujaratiSubjoinedRaY(const int lastConsY, const int consAdvancePx,
                                const GujaratiOverlayMetrics& metrics = kGujaratiOverlayMetricsDefault) {
  if (consAdvancePx <= 0 || metrics.subjoinedRaOffsetDen == 0) {
    return lastConsY;
  }
  return lastConsY - (consAdvancePx * metrics.subjoinedRaOffsetNum / metrics.subjoinedRaOffsetDen);
}

inline int gujaratiRephX(const int lastSyllableX, const int prevAdvancePx) {
  return lastSyllableX + prevAdvancePx;
}

inline int gujaratiSyllableMarkX(const int lastBaseX, const int prevAdvancePx) {
  return lastBaseX + prevAdvancePx;
}

inline int gujaratiSyllableMarkY(const int lastBaseY, const int prevAdvancePx) {
  return lastBaseY - prevAdvancePx;
}
