#!/usr/bin/env bash
#
# Cloud Agent environment bootstrap for CrossInk.
#
# Prepares a fresh Ubuntu (Cursor default image) checkout so it can:
#   * build the desktop simulator      -> pio run -e simulator
#   * build the ESP32-C3 firmware      -> pio run -e default
#   * build the ESP32-S3 firmware      -> pio run -e sticky
#   * run the headless simulator smoke -> ./scripts/run_simulator_smoke_test.py
#   * lint / statically analyse         -> ./bin/clang-format-fix, pio check
#
# The script is idempotent: it can be re-run safely and converges to the same
# state. It is intentionally non-interactive so it works inside build pipelines.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VENV_DIR="${PLATFORMIO_VENV:-$HOME/.platformio-venv}"

log() { printf '\n[install] %s\n' "$*"; }

# 1) System packages -------------------------------------------------------
# libsdl2-dev  : the native simulator renders through SDL2.
# libssl-dev   : the simulator's Linux MD5Builder links against OpenSSL libcrypto.
# libcairo2    : runtime lib for cairosvg (font/asset generation scripts).
# clang-format : formatting; version 21 is required by .clang-format (added below).
log "Installing system packages via apt"
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
  build-essential pkg-config git curl ca-certificates gnupg \
  python3 python3-venv python3-pip \
  libsdl2-dev libssl-dev libcairo2

# 2) clang-format 21 (from the LLVM apt repo; distro only ships <= 20) ------
if ! command -v clang-format-21 >/dev/null 2>&1; then
  log "Installing clang-format-21 from apt.llvm.org"
  . /etc/os-release
  curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key \
    | sudo gpg --dearmor -o /usr/share/keyrings/llvm-snapshot.gpg
  echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/${VERSION_CODENAME}/ llvm-toolchain-${VERSION_CODENAME}-21 main" \
    | sudo tee /etc/apt/sources.list.d/llvm-21.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends clang-format-21
fi

# 3) Git submodules (freeink-sdk + its nested Icons submodule) --------------
log "Initializing git submodules"
git submodule update --init --recursive

# 4) PlatformIO Core + Python tooling in an isolated venv -------------------
log "Setting up PlatformIO in $VENV_DIR"
if [ ! -x "$VENV_DIR/bin/python" ]; then
  python3 -m venv "$VENV_DIR"
fi
"$VENV_DIR/bin/pip" install -q -U pip wheel
"$VENV_DIR/bin/pip" install -q platformio
# Font-generation / tooling deps (fonttools, pillow, cairosvg, pyserial, ...).
"$VENV_DIR/bin/pip" install -q -r requirements.txt
sudo ln -sf "$VENV_DIR/bin/pio" /usr/local/bin/pio
sudo ln -sf "$VENV_DIR/bin/platformio" /usr/local/bin/platformio

# 5) Local-only PlatformIO overrides for the Linux/GCC toolchain -----------
# platformio.local.ini is git-ignored (`*.local*`). The committed flags target
# macOS/Clang; these overrides let the same envs build with Linux GCC without
# modifying the shared platformio.ini. See the file's own comments for details.
log "Writing platformio.local.ini (Linux/GCC build overrides)"
cat > platformio.local.ini <<'EOF'
; Auto-generated by .cursor/install.sh for the Cloud Agent (Linux/GCC) build.
; git-ignored via `*.local*`; do not commit. Keeps the shared platformio.ini
; (macOS/Clang oriented) untouched while letting every env build with GCC.
;
;   -Wno-narrowing : portable spelling understood by both GCC and Clang. The
;     committed flags use Clang-only `-Wno-c++11-narrowing`, so GCC otherwise
;     hard-errors on the generated web-asset blobs (src/network/html/**.h).
;   -lcrypto       : the simulator's Linux MD5Builder uses OpenSSL; the native
;     link needs libcrypto (macOS uses CommonCrypto instead).
;
; PlatformIO overrides (not appends) the global [env] build_flags when an env
; sets its own, so each leaf env is re-stated via interpolation from its parent.

[env:simulator]
build_flags =
  ${simulator-base.build_flags}
  -DCROSSINK_APP_CAP_TOUCH=0
  -DCROSSINK_FIRMWARE_DEVICE_TYPE=\"x3-x4\"
  -Wno-narrowing
  -lcrypto

[env:default]
build_flags =
  ${base.build_flags}
  -DFREEINK_DEVICE_X4=1
  -DFREEINK_DEVICE_X3=1
  -DCROSSINK_APP_CAP_TOUCH=0
  -DCROSSINK_FIRMWARE_DEVICE_TYPE=\"x3-x4\"
  -DENABLE_SERIAL_LOG
  -DLOG_LEVEL=1
  -Wno-narrowing

[env:sticky]
build_flags =
  ${base.build_flags}
  -DFREEINK_DEVICE_STICKY=1
  -DCROSSINK_APP_CAP_TOUCH=1
  -DFREEINK_FB_PSRAM=1
  -DCROSSINK_VERSION=\"${crossink.version}-sticky\"
  -DCROSSINK_FIRMWARE_DEVICE_TYPE=\"sticky\"
  -DENABLE_SERIAL_LOG
  -DLOG_LEVEL=1
  -Wno-narrowing
EOF

# 6) Warm PlatformIO packages so the first build is fast --------------------
# Native simulator toolchain + the crossink-simulator library.
log "Installing PlatformIO packages for env:simulator"
pio pkg install -e simulator
# ESP32-C3 (RISC-V) toolchain + Arduino/ESP-IDF framework for firmware builds.
log "Installing PlatformIO packages for env:default"
pio pkg install -e default

log "CrossInk environment setup complete"
