#!/usr/bin/env bash
# Lists files that comprise the Gujarati rendering integration.
# Run from the crosspoint-reader repository root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$ROOT"

echo "# Gujarati rendering — file manifest"
echo "# Generated by lib/GujaratiShaper/scripts/list-integration-files.sh"
echo

echo "## New (copy entire tree)"
find lib/GujaratiShaper -type f ! -path '*/__pycache__/*' | sort

echo
echo "## Tests"
find test/gujarati_shaper -type f 2>/dev/null | sort || true

echo
echo "## Docs"
echo docs/gujarati-rendering.md

echo
echo "## Modified (grep for Gujarati / GujaratiIntegration in fork)"
git diff --name-only HEAD -- \
  lib/Epub/Epub/ParsedText.cpp \
  lib/Epub/Epub/Section.cpp \
  lib/GfxRenderer/GfxRenderer.cpp \
  lib/EpdFont/scripts/sd-fonts.yaml \
  lib/EpdFont/scripts/fontconvert_sdcard.py \
  lib/EpdFont/scripts/build-sd-fonts.py \
  src/SdCardFontSystem.cpp \
  src/components/themes/BaseTheme.cpp \
  src/activities/reader/EpubReaderChapterSelectionActivity.cpp \
  src/activities/reader/XtcReaderChapterSelectionActivity.cpp \
  test/CMakeLists.txt \
  docs/file-formats.md \
  docs/sd-card-fonts.md \
  README.md 2>/dev/null || true
